### ISSUE TITLE
Add view composers

### ISSUE THREAD

**Issue by bhulsman** [duncan3dc/blade#1]
It would be great if we could use view composers, just like with Blade when using Laravel.

```
View::composer('sidebar', function($view) {
    $view->with('links', ['hello','world!']);
});
```

I've been digging in the Laravel (Illuminate) codebase, but I couldn't find myself what I was looking for.

**Comment by duncan3dc** [comment]
I've added this (along with `share()` and `creator()`) in version `2.1.0`

You can use it like so:

``` php
$blade->composer("sidebar", function($view) {
    $view->with("links", ["hello", "world"]);
});
```

or with the static class:

``` php
Blade::composer("sidebar", function($view) {
    $view->with("links", ["hello", "world"]);
});
```

**Comment by bhulsman** [comment]
Thanks! ^^
