### ISSUE TITLE
Cache files not automatically refreshed in development, using phpstorm

### ISSUE THREAD

**Issue by sp213** [duncan3dc/blade#13]
Hello,

Thanks for this amazing thing so that I can use it outside of Laravel.

In development, when I change the blade file and reload the browser, the changes don't immediately show up until I delete all cache files.

How can I do the immediate change for this?

Thanks!

**Comment by duncan3dc** [comment]
Hi @sessionstop, that sounds odd. Upstream doesn't have any cache settings, it just checks if the file has changed.

Are you using a remote filesystem? Is it possible that there's a delay between you pressing save and the file updating, but you're refreshing the browser too soon? The only other thing I can think of is that the filesystem is writing incorrect dates to the files, as upstream uses the last modified date of the files

**Comment by sp213** [comment]
Hi @duncan3dc,

Thanks for your reply. I am using Vagrant, installing ubuntu 16.04 LTS in it; also I am using PHPStorm. I refreshed the browser after hours, still no luck.

**Comment by sp213** [comment]
![image](https://cloud.githubusercontent.com/assets/4160306/25736844/054e1076-31a7-11e7-8d40-ead3bf58b382.png)

**Comment by duncan3dc** [comment]
Ok so the date isn't the issue, could it be a permission issue? Are you running Blade under different users each time?

**Comment by sp213** [comment]
Oh my, it really is! I change the file permission to 766, which was previously 755. Now everything is ok! My mistake. Thank you!

**Comment by duncan3dc** [comment]
No problem, glad you found the cause, happy coding :+1:
