### ISSUE TITLE
Can't use the "$this"

### ISSUE THREAD

**Issue by ghost** [duncan3dc/blade#14]
I can't use the $this instance using the blade template engine.

**Example:**
```
{{ $this->config->item() }}
{{ $this->session->flashdata() }}
```

```
Type: ErrorException
Message: Call to a member function flashdata() on null
```

**Comment by duncan3dc** [comment]
Hi there, what class/object do you expect `$this` to refer to?

**Comment by ghost** [comment]
I can't access all libraries like session, config, etc directly to my blade view using "{{ }}" unlike the ci's traditional views.

A quick fix is to call it first to controller and assign to a variable before outputting to a view, but I already used to calling it directly to my views. I also tried the get_instance() on the parent controller but still getting an error.

**Comment by duncan3dc** [comment]
Can you link to some Laravel documentation on this feature?

**Comment by ghost** [comment]
Oh I'm sorry, thought we're on the same page. I'm using this repo inside Codeigniter. I forgot to mention. I thought this was solely meant for CI until I read the description.

**Comment by duncan3dc** [comment]
Ah ok, well this project is just about making `blade` work outside of Laravel, adding other framework specific features is not in scope at this time

**Comment by duncan3dc** [comment]
You may be able to use the `share()` method to make something available to all views, like so:
```php
$blade->share("this", $codeigniter);
```
