### ISSUE TITLE
How would one get url parameters from the route request?

### ISSUE THREAD

**Issue by gkmason** [duncan3dc/blade#15]

**Comment by duncan3dc** [comment]
Hi @kyreeswilliams, [Blade](https://laravel.com/docs/5.4/blade) isn't related to routing, it is only a [templating engine](https://en.wikipedia.org/wiki/Template_processor). You'd need to get URL parameters from whatever request/routing library you are using, or `$_GET` in raw PHP

**Comment by gkmason** [comment]
My apologies @duncan3dc. I temporarily mixed this up with a Composer-included class that I'm using for routing; I meant to ask this there.
