### ISSUE TITLE
suggestion for configuration

### ISSUE THREAD

**Issue by persianphilosopher** [duncan3dc/blade#16]
First of all, thank you for this wonderful and up-to-date package; it's a gem.  

I realize that there is not much to the package itself to warrant talking to the ```.env``` file, but it would be wonderful if the asset shortcut you have provided could take variables (while keeping your prepended defaults for css/js)

I hope this is a reasonable suggestion because this package serves those us who do not want the full-Laravel treatment. I would like to be able to keep my boilerplate folder structure while making your blade repo my default viewer. Since you have made such a nice addition to blade, I thought to ask.

Thanks a bunch for your work. It is much appreciated.

**Comment by duncan3dc** [comment]
Hi @persianphilosopher, do you mean to change the path of css files?

**Comment by persianphilosopher** [comment]
@duncan3dc : thanks for your reply. It's this passage from the docs:
> However the path is optional (‘/css/’ is assumed):

It's that "assumed" part that I hope could accept options so that - for example - if I have:

public/
├── assets
│   ├── css
│   │   └── style.css

I could then use ```@mycss('styles')```  to generate:

``` <link rel='stylesheet' type='text/css' href='/assets/css/styles.css'> ```

This is obviously a bit of luxury and not that important but because of my folder structure, I have not managed to use your ```$assetify``` code. 

As I said before, I think that ```@css``` should remain the default but that one could pass an option to override it.

Does that make sense?

**Comment by duncan3dc** [comment]
Please can you try out this test version and see if it works how you require:
```sh
composer require duncan3dc/blade:dev-directives
```

```php
use duncan3dc\Laravel\Directives;
use duncan3dc\Laravel\BladeInstance;

$directives = (new Directives)
    ->withCss("assets/css")
    ->withJs("assets/js");

$blade = new BladeInstance(__DIR__ . "/views", __DIR__ . "/cache/views", $directives);
```

If you're using the static helper you can tell it to use your `BladeInstance` like so:
```php
\duncan3dc\Laravel\Blade::setInstance($blade);
```

If that all looks ok then I'll package up a release when I get a minute

**Comment by persianphilosopher** [comment]
Yes! Thank you so much. Looks like it's working (didn't test the static helper, just so you know).

**Comment by duncan3dc** [comment]
Perfect, this is in the [4.1.0](https://github.com/duncan3dc/blade/releases/tag/4.1.0) release
