### ISSUE TITLE
Non existent variable does not throw ErrorException

### ISSUE THREAD

**Issue by adakbar** [duncan3dc/blade#18]
Calling a non-existent variable seems not throw any ErrorException.

```
{{ $non_existent }}
```

It just silently running without a thing. Interesting enough, that every non-existent variable got default value of `null`.

```
@if ($non_existent == null)
    <div>It does exist, but null</div>
@endif
```

Should it be throw an ErrorException? or is it excpected behaviour?

**Comment by duncan3dc** [comment]
Hi @adakbar, this sounds like your PHP environment is configured to ignore notices.
Can you try increasing the [error_reporting](http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) level:
```php
# Report all PHP errors
error_reporting(-1);
```
That should raise an `E_NOTICE`, if you want it to throw an exception you could use [set_error_handler()](http://php.net/manual/en/function.set-error-handler.php)

**Comment by adakbar** [comment]
Gosh, stupid me. Thanks by the way.
