### ISSUE TITLE
createMatcher is undefined

### ISSUE THREAD

**Issue by TuckerWhitehouse** [duncan3dc/blade#2]
The latest version of [illuminate\view](http://github.com/illuminate/view) seems to have broken this library.
An error is thrown stating `createMatcher` is undefined in https://github.com/duncan3dc/blade/blob/master/src/Blade.php#L63

I believe the change can be seen here https://github.com/illuminate/view/compare/742f7db...de5a719

**Comment by duncan3dc** [comment]
Thanks for looking into this @TuckerWhitehouse 

I've got a solution that will be available shortly, and I'll tighten up the Laravel version dependencies to avoid problems like this in future

**Comment by duncan3dc** [comment]
Should be resolved now, you can use either 2.1.6 (for Laravel 5.0) or 2.2.0 (for Laravel 5.1)

**Comment by TuckerWhitehouse** [comment]
Awesome, thanks!
