### ISSUE TITLE
How to set default for @yield via @include file

### ISSUE THREAD

**Issue by hoangnamitc** [duncan3dc/blade#23]
![image](https://user-images.githubusercontent.com/7042462/68467776-634bc680-0249-11ea-8e8d-57a70f4b7ce9.png)

Class 'View' not found in ?

How to set default?

tks!

**Comment by duncan3dc** [comment]
Hi @hoangnamitc, I think you want to use the `@include` directive, something like:
```html
@yield('body', @include('includes.body'))
```
Does that do what you're trying to achieve?

**Comment by hoangnamitc** [comment]
Thanks Pro!

**Comment by hoangnamitc** [comment]
hi @duncan3dc  ,

I trying take your way, but return null ?

![image](https://user-images.githubusercontent.com/7042462/70386067-1d5c5c80-19c7-11ea-907f-c7347edca880.png)
