### ISSUE TITLE
Where are Document this package

### ISSUE THREAD

**Issue by hoangnamitc** [duncan3dc/blade#24]
Hi guys,

I'm can find document this package.

I'm found some method:  ->share() , ->with(), ->make() ...
I'm want find full method have into blade this and tutorial .

Thanks !

**Comment by duncan3dc** [comment]
Hi @hoangnamitc, this package just provides a way to use the Laravel Blade library without the Laravel Framework.

You can find the documentation for the Laravel Blade library here:
https://laravel.com/docs/blade
If you have any questions about this library let me know and I'll do my best to answer

**Comment by hoangnamitc** [comment]
Thanks @duncan3dc answer for me, 
So i'm can use all feature of Laravel Blade into this package.
