### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by SevenDareK** [duncan3dc/blade#3]
I use your package and I use it like that:

<?php
namespace App\Controller;

use duncan3dc\Laravel\BladeInstance;

class Controller{

```
protected $blade;

public function __construct(){
    $this->blade = new BladeInstance("src/Views");
}
```

}

and

<?php

namespace App\Controller;

use App\App\App;

class PagesController extends Controller {

```
public function show($slug){
    $data = App::getDatabase()->query('SELECT * FROM forgecms_pages WHERE slug=?', [$slug])->fetch();
    $this->blade->render('Pages.show');
}
```

}

and I don't have InvalidArgumentException but nothing display
Can you help me ?

**Comment by duncan3dc** [comment]
@SevenDareK I'm not very familiar with Laravel, but normally you'd return your view/content from your controller so it can be sent back as a response, eg:

``` php
    return $this->blade->render('Pages.show');
```
