### ISSUE TITLE
laravel 9.x support

### ISSUE THREAD

**Issue by manuzcom** [duncan3dc/blade#33]
is there any plan to support version 9?

**Comment by duncan3dc** [comment]
Hi there, I will add support as soon as I get the time :slightly_smiling_face:

**Comment by ahmed-on391** [comment]
Yes, you can upgrade to the latest version of Laravel

**Comment by duncan3dc** [comment]
Version [4.13.0](https://github.com/duncan3dc/blade/releases/tag/4.13.0) of this library is compatible with Laravel 8, 9, and 10
