### ISSUE TITLE
View [categories.create] not found.

### ISSUE THREAD

**Issue by ahmed-on391** [duncan3dc/blade#34]
I wanted to display the categories[ ](https://i.stack.imgur.com/hOrjb.png

  And then click on create This page appears[enter image description here](https://i.stack.imgur.com/g5GLc.png)
I have tried to solve the problem but could not please help

**Comment by duncan3dc** [comment]
Hi @ahmed-on391 this doesn't look like an issue with the library, but more likely an issue with your setup.

Can you share your directory/file structure?
