### ISSUE TITLE
Please add support for PHP 8.2

### ISSUE THREAD

**Issue by kmilo2622** [duncan3dc/blade#35]
In this moment when we try to use the package with php8.2 gives a fatal error and there is not any update of this package. Other packages too don't have support for php8.2

![image](https://user-images.githubusercontent.com/17767356/217368069-d3684bb3-2633-42c1-937d-4de5ea47d96a.png)

**Comment by duncan3dc** [comment]
Version [4.12.0](https://github.com/duncan3dc/blade/releases/tag/4.12.0) was just released which contains support for PHP 8.1, 8.2 and 8.3
