### ISSUE TITLE
I've got Problem when I try install it with Symfony.

### ISSUE THREAD

**Issue by SmirnovW** [duncan3dc/blade#7]
I want to try Blade in Symfony instead of Twig. For this I try install your Blade implementation, but I have a problem during installation:

>   Problem 1
>     - Conclusion: remove symfony/symfony v3.1.2
>     - Conclusion: don't install symfony/symfony v3.1.2
>     - duncan3dc/blade 2.2.0 requires illuminate/view ~5.1.0 -> satisfiable by illuminate/view[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1
> .8].
>     - duncan3dc/blade 2.2.1 requires illuminate/view ~5.1.0 -> satisfiable by illuminate/view[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1
> .8].
>     - illuminate/view v5.1.1 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
> v5.1.6, v5.1.8].
>     - illuminate/view v5.1.13 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.16 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.2 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
> v5.1.6, v5.1.8].
>     - illuminate/view v5.1.20 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.22 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.25 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.28 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.30 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.31 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
>  v5.1.6, v5.1.8].
>     - illuminate/view v5.1.6 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
> v5.1.6, v5.1.8].
>     - illuminate/view v5.1.8 requires illuminate/filesystem 5.1.\* -> satisfiable by illuminate/filesystem[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41,
> v5.1.6, v5.1.8].
>     - illuminate/filesystem v5.1.1 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2
> .7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.13 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.16 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.2 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2
> .7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.20 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.22 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.25 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.28 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.30 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.31 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.41 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v
> 2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.6 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2
> .7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/filesystem v5.1.8 requires symfony/finder 2.7.\* -> satisfiable by symfony/finder[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2
> .7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - illuminate/view v5.1.41 requires symfony/debug 2.7.\* -> satisfiable by symfony/debug[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.2, v2.7.3, v2.7.4, v2.7.5, v
> 2.7.6, v2.7.7, v2.7.8, v2.7.9].
>     - don't install symfony/finder v2.7.0|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.1|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.10|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.11|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.12|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.13|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.14|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.15|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.16|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.2|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.3|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.4|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.5|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.6|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.7|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.8|don't install symfony/symfony v3.1.2
>     - don't install symfony/finder v2.7.9|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.0|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.1|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.10|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.11|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.12|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.13|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.14|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.15|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.16|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.2|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.3|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.4|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.5|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.6|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.7|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.8|don't install symfony/symfony v3.1.2
>     - don't install symfony/debug v2.7.9|don't install symfony/symfony v3.1.2
>     - Installation request for symfony/symfony (locked at v3.1.2, required as 3.1.*) -> satisfiable by symfony/symfony[v3.1.2].
>     - Installation request for duncan3dc/blade ^2.2 -> satisfiable by duncan3dc/blade[2.2.0, 2.2.1].

This is my composer.json

> {
>     "name": "symfony/framework-standard-edition",
>     "license": "MIT",
>     "type": "project",
>     "description": "The \"Symfony Standard Edition\" distribution",
>     "autoload": {
>         "psr-4": { "": "src/" },
>         "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
>     },
>     "autoload-dev": {
>         "psr-4": { "Tests\": "tests/" }
>     },
>     "require": {
>         "php": ">=5.5.9",
>         "symfony/symfony": "3.1.*",
>         "doctrine/orm": "^2.5",
>         "doctrine/doctrine-bundle": "^1.6",
>         "doctrine/doctrine-cache-bundle": "^1.2",
>         "symfony/swiftmailer-bundle": "^2.3",
>         "symfony/monolog-bundle": "^2.8",
>         "symfony/polyfill-apcu": "^1.0",
>         "sensio/distribution-bundle": "^5.0",
>         "sensio/framework-extra-bundle": "^3.0.2",
>         "incenteev/composer-parameter-handler": "^2.0"
>     },
>     "require-dev": {
>         "sensio/generator-bundle": "^3.0",
>         "symfony/phpunit-bridge": "^3.0"
>     },
>     "scripts": {
>         "post-install-cmd": [
>             "Incenteev\ParameterHandler\ScriptHandler::buildParameters",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget"
>         ],
>         "post-update-cmd": [
>             "Incenteev\ParameterHandler\ScriptHandler::buildParameters",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile",
>             "Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget"
>         ]
>     },
>     "config": {
>         "platform": {
>             "php": "5.5.9"
>         }
>     },
>     "extra": {
>         "symfony-app-dir": "app",
>         "symfony-bin-dir": "bin",
>         "symfony-var-dir": "var",
>         "symfony-web-dir": "web",
>         "symfony-tests-dir": "tests",
>         "symfony-assets-install": "relative",
>         "incenteev-parameters": {
>             "file": "app/config/parameters.yml"
>         },
>         "branch-alias": {
>             "dev-master": "3.1-dev"
>         }
>     }
> }

In 
May be you know how I can solve this problem? 
Thanks!

**Comment by duncan3dc** [comment]
Unfortunately the [latest release](https://github.com/illuminate/filesystem/blob/df115e3cc4444f340064a3e20e16eed9c25e8263/composer.json#L20) of Laravel does not support Symfony 3.1 components.

It [looks like](https://github.com/illuminate/filesystem/blob/c57b73eb32dca879d3f4b686a1c3777a1d803852/composer.json#L20) they are planning to support them in Laravel 5.3, but until that is released it won't be possible to installed stable versions of Laravel and Symfony 3.1 together

**Comment by SmirnovW** [comment]
@duncan3dc in any case, thank you for answer!
