### ISSUE TITLE
throw new InvalidArgumentException("View [$name] not found.");

### ISSUE THREAD

**Issue by seth0** [duncan3dc/blade#8]
Hello,

Im learning PHP and im following a course via a website. The instructor uses this package for templating. And we learned about using routes controllers etc. 
Now we switched from Twig -> Blade. And im having a problem.

This is my BaseController.php

``` php
namespace Nrs\controllers;

use duncan3dc\Laravel\BladeInstance;

class BaseController
{
    protected $Blade;

    public function __construct()
    {
        $this->Blade = new BladeInstance("/views/", "/cache/views/");
    }
}
```

And this is my PageController:

``` php
namespace Nrs\controllers;

use duncan3dc\Laravel\BladeInstance;
class PageController extends BaseController
{
    public function getShowHomePage()
    {
      echo $this->Blade->render("home");
    }
}
```

Im getting the error in my Title of this issue.
Getting stuck for ever now. Hope i allowed here to post it. 
Sorry for my English
Tino

**Comment by duncan3dc** [comment]
The first thing I notice is that you're using full paths in your constructor:

``` php
new BladeInstance("/views/", "/cache/views/");
```

Where is your "views" folder located? It's probably not in the root of the filesystem (`/views`).
Is it somewhere like `/var/www/webapp/views`?

**Comment by seth0** [comment]
Goodmorning Duncan3dc, 

Thanks for your answer. 
Im learning via XAMPP -> so this is my folder structure:

![duncanimgur](https://cloud.githubusercontent.com/assets/18310280/17729880/8a68a366-6466-11e6-9468-5e9457244fc5.png)

**Comment by duncan3dc** [comment]
Yeh so it looks like your full path is

``` php
new BladeInstance("/opt/lampp/htdocs/views", "/opt/lampp/htdocs/cache/views");
```

Or you could use relative paths from your controllers file:

``` php
new BladeInstance(__DIR__ . "/../../views", __DIR__ . "/../../cache/views");
```

**Comment by seth0** [comment]
That was the Answer! Thank you so much
