### ISSUE TITLE
Parser error on webhost

### ISSUE THREAD

**Issue by rafmst** [duncan3dc/blade#9]
I'm getting the follow error on my webhost, on my localhost everything is okay:

``` php
syntax error, unexpected '.'
```

And this is triggered in line 63:

``` php
public static function __callStatic($name, array $arguments)
{
        return static::getInstance()->$name(...$arguments);
}
```

Any ideas what could be wrong?
Thanks

**Comment by duncan3dc** [comment]
It sounds like your webhost is running an [unsupported version](http://php.net/supported-versions.php) of PHP.

The syntax that is failing is called [Variadic functions](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list) and was added in PHP 5.6

**Comment by rafmst** [comment]
Upgraded my host to php7.0 and it is working now. I guess you should not worry to much with getting that working on < 5.6 versions of PHP, but this is just my personal opinion.

Thanks for your fast reply, and congratulations on the cool project here
Cheers from Portugal 👍

**Comment by duncan3dc** [comment]
Glad it's working, happy coding!

**Comment by rafmst** [comment]
Hi @duncan3dc, I got this error again, but this time I can't change the hosting PHP version. Any idea how to hackishly solve this for now? Thanks

**Comment by duncan3dc** [comment]
You could try using [call_user_func_array()](http://php.net/manual/en/function.call-user-func-array.php) instead. Something like this:

``` php
public static function __callStatic($name, array $arguments)
{
    $instance = static::getInstance();
    return call_user_func_array([$instance, $name], $arguments);
}
```
